### ISSUE TITLE
Изменение кнопки отправить

### ISSUE THREAD

**Issue by Ka-ra-siK** [januarydayfin/ClipperIssues#2]
Сейчас не совсем интуитивно понятно, что пользователь может после ввода текста отправить его в список, так как иконка "вставить из буфера обмена" в сроке с вводом текста не меняется, нужно заменить ее на стрелку.
![до ввода](https://github.com/januarydayfin/ClipperIssues/assets/53082951/1909c9ad-146f-4d99-8524-d08e4f1fc25a)
![после ввода](https://github.com/januarydayfin/ClipperIssues/assets/53082951/45317938-58ea-411c-89b5-7bf76a7eb077)

**Comment by januarydayfin** [comment]
Тоже так считаю, передам дизайнеру. Наверное стоит изменять иконку

**Comment by januarydayfin** [comment]
Исправлено
