### ISSUE TITLE
После перезагрузки сбрасывается виджет

### ISSUE THREAD

**Issue by Ka-ra-siK** [januarydayfin/ClipperIssues#4]
После перезагрузки устройства, виджет сбрасывается, хотя данные есть в приложении.
![Screenshot_20240229-073649_One UI Home](https://github.com/januarydayfin/ClipperIssues/assets/53082951/68b6e0a6-b4cf-4f7e-bc5d-8e03edf00b5d)
![Screenshot_20240229-073703_Clipper](https://github.com/januarydayfin/ClipperIssues/assets/53082951/7871d04f-9d9e-42d6-adfa-f75df39a37d7)

**Comment by januarydayfin** [comment]
Немного изменил работу виджета, будет в 1.04
